name: controldegastosapp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.19.6
  firebase_core: ^2.31.1
  fl_chart: ^0.68.0
  intl: ^0.18.0 # Añade esta línea para intl
  flutter_native_splash: ^2.4.0
  high_chart: ^2.1.0
  mrx_charts: ^0.1.3

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  provider: ^6.1.2

flutter_native_splash:
  color: "#003131"
  image: "assets/splash.png"
  android_12:
    image: "assets/splash.png"

flutter:
  uses-material-design: true
