// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHsOzShdrMLgPVmv_PXbj3jAOjxlz2YFc',
    appId: '1:869560800451:android:8828bd4de5f43b474cfe76',
    messagingSenderId: '869560800451',
    projectId: 'gastosapp-90914',
    storageBucket: 'gastosapp-90914.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaF1ESSx_KcRbSD5TXIHXsz8d_jheyv3c',
    appId: '1:869560800451:web:cf15650410082a0d4cfe76',
    messagingSenderId: '869560800451',
    projectId: 'gastosapp-90914',
    authDomain: 'gastosapp-90914.firebaseapp.com',
    storageBucket: 'gastosapp-90914.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM1qcu4AeqNOUMxnXzxldxMN535ZBoQ5Y',
    appId: '1:869560800451:ios:d9cc3773fa0344974cfe76',
    messagingSenderId: '869560800451',
    projectId: 'gastosapp-90914',
    storageBucket: 'gastosapp-90914.appspot.com',
    iosBundleId: 'com.example.controldegastosapp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM1qcu4AeqNOUMxnXzxldxMN535ZBoQ5Y',
    appId: '1:869560800451:ios:d9cc3773fa0344974cfe76',
    messagingSenderId: '869560800451',
    projectId: 'gastosapp-90914',
    storageBucket: 'gastosapp-90914.appspot.com',
    iosBundleId: 'com.example.controldegastosapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaF1ESSx_KcRbSD5TXIHXsz8d_jheyv3c',
    appId: '1:869560800451:web:aa2d2315c3ed4b674cfe76',
    messagingSenderId: '869560800451',
    projectId: 'gastosapp-90914',
    authDomain: 'gastosapp-90914.firebaseapp.com',
    storageBucket: 'gastosapp-90914.appspot.com',
  );

}